export type ArchiveDetail = {
  region?: string; abv?: string; cooking?: string; extraction?: string;
  fermentation?: string; distillation?: string; aging?: string; agave?: string;
  style?: string; plantAge?: string; aroma?: string; taste?: string;
  image?: string; sourceLabel?: string;
};

export const archiveDetails: Record<string, ArchiveDetail> = {
  "1800 SILVER": {
    "region": "Jalisco (Los Valles),",
    "abv": "40% abv (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Alcohol · Agave (Cooked) · Pepper · Citrus · Butter · Earth · Sweet Fruit",
    "taste": "Alcohol · Pepper · Agave (Cooked) · Citrus · Acetone · Smoke",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "1800 REPOSADO": {
    "region": "Jalisco (Los Valles),",
    "abv": "40% abv (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "French Oak Barrels - No less than 6 months",
    "aroma": "Agave (Cooked) · Vanilla · Alcohol · Oak · Caramel · Pepper. Cinnamon",
    "taste": "Agave (Cooked) · Alcohol · Oak · Pepper · Caramel · Smoke · Vanilla",
    "image": "/images/agave/1800-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "1800 AÑEJO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autocave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "French Oak Barrels - Minimum 14 Months",
    "aroma": "Oak · Vanilla · Agave (Cooked) · Alcohol · Whisky · Caramel · Smoke",
    "taste": "Oak · Vanilla · Agave (Cooked) · Alcohol · Caramel · Pepper · Clove",
    "image": "/images/agave/1800-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASA MAESTRI BLANCO": {
    "region": "Jalisco (Los Valles)",
    "abv": "35%-39% (70-78 proof)",
    "cooking": "Autoclave (high pressure) · Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Herbal · Aloe · Eucalyptus · Guanabana · Honey · Agave (Cooked)",
    "taste": "Herbal · Aloe · Eucalyptus · Guanabana · Honey · Poblano · Spices",
    "image": "/images/agave/casa-maestri-reserva-de-mfm-blanco.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASA MAESTRI REPOSADO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (high pressure) · Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "100% Agave · Stainless Steel Tanks",
    "aging": "Oak Barrels · Upto 1 Year",
    "aroma": "Vanilla · Butter · Cream Soda · Oak · Agave (Raw) · Citrus · Caramel",
    "taste": "Vanilla · Pepper · Oak · Raisin · Butter · Caramel · Butterscotch",
    "image": "/images/agave/casa-maestri-reserva-de-mfm-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASA MAESTRI AÑEJO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Oak Barrels · No less than 1 year",
    "aroma": "Agave · Vanilla · Oak · Butter · Caramel · Pepper · Cinnamon · Grass",
    "taste": "Agave (Raw) · Agave (Cooked) · Butter · Earth · Vanilla · Pepper",
    "image": "/images/agave/casa-maestri-reserva-de-mfm-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASAMIGOS BLANCO": {
    "region": "Jalisco (Los Valtos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Agave (Cooked) · Vanilla · Citrus · Pepper · Caramel · Floral · Earth",
    "taste": "Agave (Cooked) · Vanilla · Citrus · Pepper · Caramel · Floral · Cake",
    "image": "/images/agave/casamigos-blanco.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASAMIGOS REPOSADO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American White Oak Whisky Barrel · 7 Months",
    "aroma": "Vanilla · Caramel · Agave (Cooked) · Oak · Butter · Cinnamon · Cacao",
    "taste": "Caramel · Vanilla · Agave (Cooked) · Oak · Butterscotch · Butter",
    "image": "/images/agave/casamigos-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASAMIGOS AÑEJO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American White Oak Whisky Barrel · 14 Months",
    "aroma": "Caramel · Vanilla · Agave (Cooked) · Oak · Cinnamon · Butterscotch",
    "taste": "Caramel · Agave (Cooked) · Vanilla · Oak · CInnamon · Whisky · Smoke",
    "image": "/images/agave/casamigos-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CAZADORES BLANCO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (Post Diffuser)",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks · Classical Music",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Agave (Cooked) · Alcohol · Agave (Raw) · Acetone · Caramel · Banana",
    "taste": "Alcohol · Agave (Cooked) · Medicinal · Caramel · Acetone · Banana",
    "image": "/images/agave/cazadores-blanco.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CAZADORES REPOSADO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (Post Diffuser)",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks · Classical Music",
    "distillation": "x2 Distilled",
    "aging": "New American White Oak Barrels · 2 Months",
    "aroma": "Alcohol · Agave (Cooked) · Vanilla · Oak · Earth · Caramel · Agave (Raw)",
    "taste": "Alcohol · Vanilla · Agave (Cooked) · Caramel · Earth · Clove · Oak",
    "image": "/images/agave/cazadores-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CAZADORES AÑEJO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (Post Diffuser)",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks · Classical Music",
    "distillation": "x2 Distilled",
    "aging": "New American White Oak Barrels · 12 Months Minimum",
    "aroma": "Agave (Cooked) · Oak · Vanilla · Caramel · Whisky · Cinnamon · Honey",
    "taste": "Oak · Agave (Cooked) · Vanilla · Butterscotch · Pepper · Whisky · Honey",
    "image": "/images/agave/cazadores-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CENOTE AÑEJO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American White Oak Bourbon Barrels · 1 Year",
    "aroma": "Vanilla · Caranmel · Agave (Cooked) · Oak · Butterscotch · Whisky",
    "taste": "Vanilla · Oak · Caramel · Agave (Cooked) · CInnamon · Chocolate",
    "image": "/images/agave/cenote-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CLASE AZUL PLATA": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "100% Agave · Stainless Steel Tanks",
    "taste": "Agave (Cooked) · Vanilla · Pepper · Caramel · Cream Soda · Mint · Cinnamon",
    "image": "/images/agave/clase-azul-plata.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CLASE AZUL REPOSADO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "100% Agave · Stainless Steel Tanks",
    "aging": "Used American White Oak Bourbon Barrels · 8 Months",
    "taste": "Vanilla · Caramel · Agave (Cooked) · Oak · Pepper · Honey · Butter",
    "image": "/images/agave/clase-azul-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CLASE AZUL AÑEJO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American White Oak Bourbon Barrels · 25 Months",
    "aroma": "Agave (Cooked) · Citrus · Pepper · Alcohol · Vanilla · Vegetal · Yeast · Earth",
    "taste": "Vanilla · Caramel · Oak · Butterscotch · Clove · Nutmeg · Banana",
    "image": "/images/agave/clase-azul-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "DON JULIO BLANCO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distillation",
    "taste": "Agave (Cooked) · Pepper · Citrus · Vanilla · White Pepper · Earth · Butter",
    "image": "/images/agave/don-julio-silver.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "DON JULIO REPOSADO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "100% Agave · Stainless Steel Tanks",
    "aging": "Bourbon Barrels · 8 Months",
    "taste": "Vanilla · Caramel · Agave (Cooked) · Oak · Pepper · Honey · Butter · Cinnamon",
    "image": "/images/agave/don-julio-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "DON JULIO 1942 EXTRA AÑEJO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "100% Agave · Stainless Steel Tanks",
    "aging": "Bourbon Barrels · 36 Months",
    "taste": "Vanilla · Caramel · Agave (Cooked) · Oak · Pepper · Honey · Butter",
    "image": "/images/agave/don-julio-1942.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "ESPOLON BLANCO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Agave (Cooked) · Alcohol · Pepper · Citrus · Vanilla · Grass · Butter",
    "taste": "Agave (Cooked) · Pepper · Alcohol · Citrus · Vanilla · White Pepper",
    "image": "/images/agave/espolon-blanco.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "ESPOLON REPOSADO": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "American White Oak Barrels · 6 Months",
    "aroma": "Agave (Cooked) · Oak · Caramel · Alcohol · Vanilla · Pepper · Butter",
    "taste": "Agave (Cooked) · Oak · Pepper · Caramel · Alcohol · Butterscotch",
    "image": "/images/agave/espolon-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "GRAN CORONEL REPOSADO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "French & American Oak Barrels · 6 Months Minimum",
    "aroma": "Oak · Molasses · Whisky · Alcohol · Bread · Spice · Tobacco",
    "taste": "Toasted Bread · Smoke · Spices · Vanilla · Oak · Tobacco · Whisky",
    "image": "/images/agave/gran-coronel-tequila-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "HORNITOS BLACK BARREL": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Diffuser",
    "fermentation": "100% Agave",
    "distillation": "x2 Distilled",
    "aging": "Toasted Oak · 12 months · Charred Oak · 4 Months · Toasted Oak · 2 Months",
    "aroma": "Whisky · Agave (Cooked) · Oak · Vanilla · Caramel · Smoke · Pepper",
    "taste": "Whisky · Oak · Agave (Cooked) · Smoke · Vanilla · Pepper · Caramel",
    "image": "/images/agave/hornitos-black-barrel-anejo.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "HUSSONG'S REPOSADO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Diffuser",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used Bourbon Barrels · 5 Months",
    "aroma": "Citrus · Vanilla · Grass · Agave (Cooked) · Licorice · Almond · Herbal",
    "taste": "Agave (Cooked) · Cinnamon · Pepper · Butter · Caramel · Vanilla · Pineapple",
    "image": "/images/agave/hussong-s-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LA PINTA POMEGRANATE TEQUILA": {
    "region": "Jalisco (Los Altos Southern)",
    "abv": "19%",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "100% Agave · Stainless Steel Tanks",
    "aroma": "Sweet · Fruity · Pomegranate · Agave · Alcohol",
    "taste": "Sweet · Fruity · Pomegranate · Agave · Alcohol",
    "image": "/images/agave/la-pinta-pomegranate.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS ARANGO REPOSADO": {
    "region": "Guanajuato",
    "abv": "35%-39% (70-78 porrod",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "American Oak · 7 Months",
    "aroma": "Agave (Cooked) · Alcohol · White Pepper · Jalapeño · Pepper · Caramel",
    "taste": "White Pepper · Agave (Cooked) · Pepper · Jalapeño · Caramel · Citrus",
    "image": "/images/agave/los-arango-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS AZULEJOS SILVER": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (High Pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Pepper · Agave (Raw) · Lemon · Anise · Tropical Fruits · Vegetal · Grass",
    "taste": "Agave (Raw) · Pepper · Tropical Fruits · Lemon · Citrus · White Pepper",
    "image": "/images/agave/los-azulejos-silver.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS AZULEJOS REPOSADO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Diffuser",
    "fermentation": "100% Agave",
    "distillation": "x2 Distilled",
    "aging": "Used Bourbon Barrels · 8 Months",
    "aroma": "Agave (Cooked) · Grapefruit · Pepper · Citrus · Earth · Pear ·  Vanilla",
    "taste": "Pear · Vanilla · Alcohol · Vegetal · Cinnamon",
    "image": "/images/agave/los-azulejos-reposado.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS AZULEJOS AÑEJO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Diffuser",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Oak Barrels · Almost 3 Years",
    "aroma": "Caramel · Vanilla · Butterscotch · Agave (Cooked) · Oak · Cherry · Pineapple",
    "taste": "Vanilla · Agave (Cooked) · Caramel · Oak · Pepper · Cinnamon · Butterscotch",
    "image": "/images/agave/los-azulejos-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "MAESTRO DOBEL TEQUILA": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% ABV (80-proof)",
    "cooking": "Autoclave (high pressure)",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "New European Oak Barrels · 1, 2, & 3 Year Blended",
    "aroma": "Agave (Cooked) · Alcohol · Pepper · Vanilla · Citrus · Floral · Caramel · Oak",
    "taste": "Agave (Cooked) · Pepper · Alcohol · Vanilla · Oak · White Pepper · Citrus",
    "image": "/images/agave/maestro-dobel-diamond-anejo-extra-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "MILAGRO REPOSADO": {
    "region": "Jalisco (Los Altos)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "New American & French Oak Barrels · 3 to 6 months",
    "aroma": "Agave (Cooked) · Oak · Vanilla · Caramel · Earth · Cinnamon · Orange Peel",
    "taste": "Oak · Agave (Cooked) · Vanilla · Caramel · Butter · Earth · Pepper · Banana",
    "image": "/images/agave/milagro-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "PATRON SILVER": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% ABV (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Tahona · Roller Mill",
    "fermentation": "100% Agave · Wooden Fermentation Tanks · Charcoal Filtration",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Agave (Cooked) · Pepper · Citrus · Alcohol · Fruity · Earth · Vailla · Lime",
    "taste": "Agave (Cooked) · Pepper · Citrus · Fruity · Vanilla · Lime · Agave (Raw)",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "PATRON REPOSADO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Tahona · Roller Mill",
    "fermentation": "100% Agave · Wooden Fermentation Tanks · Charcoal Filtration",
    "distillation": "x2 Distilled",
    "aging": "French Oak Barrels · American White Oak Barrels · Hybrid Barrels · 2 Mnths",
    "aroma": "Agave (Cooked) · Vanilla · Caramel · Pepper · Butter · Citrus · Lemon",
    "taste": "Agave (Cooked) · Pepper · Butter · Cinnamon · Vanilla · Honey · Oak",
    "image": "/images/agave/patron-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "PATRON AÑEJO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Tahona · Roller Mill",
    "fermentation": "100% Agave · Wooden Fermentation Tanks · Charcoal Filtration",
    "distillation": "x2 Distilled",
    "aging": "French Oak Barrels · American White Oak Barrels · Hybrid Barrels · 12 Months",
    "aroma": "Agave (Cooked) · Vanilla · Oak · Honey · Caramel · Nuts · Pepper · Banana",
    "taste": "Agave (Cooked) · Vanilla · Oak · Honey · Pepper · Caramel · Nuts · Cinnamon",
    "image": "/images/agave/patron-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SAUZA TRES GENERACIONES PLATA": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (Post Diffuser)",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks · Organic",
    "distillation": "x3 Distilled",
    "aging": "N/A",
    "aroma": "Herbal · Earthy · Spicy · Pepper · Citrus · Floral · Melon · All Spice",
    "taste": "Herbal · Earthy · Spicy · Pepper · Citrus · Floral · Green Pepper · Tobacco",
    "image": "/images/agave/sauza-tres-generaciones-plata.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SAUZA TRES GENERACIONES REPOSADO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (Post Diffuser)",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks · Organic",
    "distillation": "x3 Distilled",
    "aging": "Used American Oak Bourbon Barrels · 4 Months",
    "aroma": "Oak · Agave (Cooked) · Pepper · Spices · Herbal · Caramel",
    "taste": "Citrus · Earthy · Oak · Agave (Cooked) · Light Mint · Toasted Notes",
    "image": "/images/agave/sauza-tres-generaciones-reposado.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SAUZA TRES GENERACIONES AÑEJO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Autoclave (Post Diffuser)",
    "extraction": "Diffuser",
    "fermentation": "100% Agave · Stainless Steel Tanks · Organic",
    "distillation": "x3 Distilled",
    "aging": "Used American Oak Bourbon Barrels · Minimum 3 Years",
    "aroma": "Toasted Oak · Agave (Cooked) · Caramel · Vanilla · Molasses",
    "taste": "Brown Sugar · Oak · Buttercream · Baking Spices · Light Smoke",
    "image": "/images/agave/sauza-tres-generaciones-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SIEMPRE PLATA": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Sonte/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks · Open-Air Fermentation",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Agave (Cooked) · Citrus · Pepper · Earth · Grass · Vanilla · Herbal · Tropical",
    "taste": "Agave (Cooked) · Pepper · Citrus · Earth · Grass · Caramel · Spices · Pear",
    "image": "/images/agave/siempre-plata.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SIEMPRE AÑEJO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks · Open-Air Fermentation",
    "distillation": "x2",
    "aging": "Used Bourbon Barrels · 12 Months",
    "aroma": "Oak · Agave (Cooked) · Caramel · Vanilla · Toffe · Butterscotch",
    "taste": "Oak · Agave (Cooked) · Caramel · Spices · Butter · Vanilla · Cherries · Tropical",
    "image": "/images/agave/siempre-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS AZULEJOS 'SKELLY' BLANCO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Butterscotch · Agave (Cooked) · Butter · Cherry · Caramel · Chocolate",
    "taste": "Butterscotch · Agave (Cooked) · Butter · Cherry · Caramel · Chocolate",
    "image": "/images/agave/los-azulejos-skeleto-blanco.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS AZULEJOS SKELLY REPOSADO": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American Bourbon Oak Barrels · 8 - 12 Months",
    "aroma": "Vanilla · Toffe · Earth · Smoke · Caramel · Butter · Cream · Oak · Mineral",
    "taste": "Vanilla · Toffe · Earth · Smoke · Caramel · Butter · Oak · Mineral · Grapefruit",
    "image": "/images/agave/los-azulejos-skeleto-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS AZULEJOS SKELLY AÑEJO BANDITO LTD": {
    "region": "Jalisco (Los Valles)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used French Cognac · 18 - 30 Months",
    "aroma": "Vanilla · Cream Soda · Agave (Cooked) · Oak · Molasses · Baking Spices",
    "taste": "Vanilla · Cream Soda · Agave (Cooked) · Oak · Molasses · Baking Spices",
    "image": "/images/agave/los-azulejos-skeleto-anejo.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "TROMBA BLANCO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "N/A",
    "aroma": "Agave (Cooked) · Pepper · Citrus · Fruity · Earth · Vegetal · Vanilla · Mint",
    "taste": "Agave (Cooked) · Pepper · Citrus · Fruity · Earth · Vegetal · Vanilla · Butter",
    "image": "/images/agave/tromba-blanco.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "TROMBA REPOSADO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American White Oak Bourbon Barrels · 6 Months",
    "aroma": "Agave (Cooked) · Vanilla · Pepper · Citrus · Oak · Caramel · Banana · Clove",
    "taste": "Agave (Cooked) · Citrus · Banana · Pepper · Oak · Vanilla · Caramel · Earth",
    "image": "/images/agave/tromba-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "TROMBA AÑEJO": {
    "region": "Jalisco (Ciénega)",
    "abv": "40% (80-proof)",
    "cooking": "Stone/Brick Ovens",
    "extraction": "Roller Mill",
    "fermentation": "100% Agave · Stainless Steel Tanks",
    "distillation": "x2 Distilled",
    "aging": "Used American White Oak Bourbon Barrels · 20 Months Minimum",
    "aroma": "Agave (Cooked) · Caramel · Vanilla · Earth · Pepper · Fruity · Oak · Tropical",
    "taste": "Agave (Cooked) · Caramel · Vanilla · Oak · Pepper · Grapefruit · Caraway",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "AGUA SANTA JOVEN": {
    "region": "Oaxaca",
    "abv": "42%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "7-8 Years",
    "aroma": "Soft Smoke · Crisp · Earth · Tropical · Spices",
    "taste": "Soft Smoke · Crisp · Earth · Tropical",
    "image": "/images/agave/agua-santa.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "AMORES MOMENTO MEZCAL VERDE": {
    "region": "Oaxaca",
    "abv": "43%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "8 Years",
    "aroma": "Soft Smoke · Crisp · Peach · Tropical · Sugared Almonds",
    "taste": "Soft Smoke · Crisp · Earth · Tropical · Grass",
    "image": "/images/agave/amores-verde-momento.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "AMORES ESPADIN": {
    "region": "Oaxaca",
    "abv": "41%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "7-8 Years",
    "aroma": "Vanilla · Chocolate · Smoke · Chestnuts · Caramel",
    "taste": "Floral · Orange · Pineapple · Tropical · Bright · Perfume",
    "image": "/images/agave/amores-espadin-joven.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "AMORES REPOSADO": {
    "region": "Oaxaca",
    "abv": "37%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "9 Years",
    "aroma": "Warm Wood · Agave (cooked) · Toasted Hazelnut",
    "taste": "Vanilla · Wet Wood · Subtle · Long",
    "image": "/images/agave/amores-reposado.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "AMORES CUPREATA": {
    "region": "Oaxaca",
    "abv": "40%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "7-8 Years",
    "aroma": "Roasted Pumpkin Seeds · Leather · Cocoa · Banana Leaves · Green Herbs",
    "taste": "Soft SMoke · Agave · Fruit · Pepper · Citrus · Vanilla · Cinnamon · Brown Sugar",
    "image": "/images/agave/amores-cupreata.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "AMORES CENZIO LOGIA": {
    "region": "Durango",
    "abv": "46%",
    "agave": "Cenizo",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "14 Years",
    "aroma": "Fruit · Earth · Sweet Chipotle · Bell Pepper · Dried Oregano · Bubblegum",
    "taste": "Toasted Coffee · Wood Spice · Raisin Bread · Grilled Green Papaya · Underripe Pineapple",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "BOSSCAL": {
    "region": "Durango",
    "abv": "42%",
    "agave": "Cenizo",
    "extraction": "By Hand with Axes · Cooked in Volcanic Rock Ovens",
    "style": "Joven",
    "distillation": "Steel",
    "plantAge": "8-10 Years",
    "aroma": "Slight Smoke · Floral · Herbal · Minerals · Tropical · Banana · Kiwi",
    "taste": "Light Smoke · Crisp · Citrus · Blood Orange · Fruit",
    "image": "/images/agave/bosscal.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CASAMIGOS": {
    "region": "Santiago Matatlan, Oaxaca",
    "abv": "40%",
    "agave": "Espadin",
    "extraction": "Roller Mill",
    "style": "Joven",
    "distillation": "Copper",
    "aroma": "Smoke · Herbal · Cucumber · Tropical  · White Pepper",
    "taste": "Tamarind ·  Pomegranate · Banana · Mango · Herbal · Oregano · Smoke · Licorice",
    "image": "/images/agave/casamigos.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "CLASE AZUL": {
    "region": "Durango",
    "abv": "40%",
    "agave": "Espadin",
    "extraction": "Cenizo",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "12-15 Years",
    "aroma": "Smoke · Sweet · Agave (Roasted) · Spicy · Caramel · Vanilla · Oak · Sherry",
    "taste": "Smoke · Sweet · Agave (Roasted) · Spicy · Caramel · Vanilla · Oak · Sherry",
    "image": "/images/agave/clase-azul.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LEYENDA 'TLACUACHE'": {
    "region": "San Juan del Rio, Oaxaca",
    "abv": "42%",
    "agave": "Espadin",
    "extraction": "Horse Drawn Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "9 Years",
    "aroma": "Lemongrass · Herbal · Cane Sugar · Citrus · Earth · Smoke",
    "taste": "Apples · Pear · Roasted Agave · Smoke · Herbal · Citrus",
    "image": "/images/agave/leyenda-tlachuache.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "LOS SIETE MISTERIO": {
    "region": "Santiago Matatlan, Oaxaca",
    "abv": "45.5%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Clay Pots",
    "plantAge": "7-9 Years",
    "aroma": "Citrus · Melon · Mint · Herbs · Orange · Apple ·  Toasted Caramel · Violet",
    "taste": "Spice · Honey · Clove · Toasted Oak · Toffee",
    "image": "/images/agave/los-siete-misterios-doba-yej.jpeg",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SANTO PURO MEZQUILA": {
    "region": "Guadalajara, Jalisco,",
    "abv": "39.5%",
    "agave": "50% Blue Variety Tequilana Weber agave  50% Espadin",
    "extraction": "Tahona",
    "style": "Tequila & Mexcal Mix",
    "distillation": "Copper",
    "plantAge": "7-8 Years",
    "aroma": "Smoke · Citrus · Herbal · Sea Salt · Oak · Toffee · Caramel",
    "taste": "Smoke · Citrus · Herbal · Sea Salt · Oak · Bubblegum · Toffee",
    "image": "/images/agave/santa-puro-mezquila.png",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  },
  "SOMBRA JOVEN": {
    "region": "San Juan del Rio, Oaxaca",
    "abv": "45%",
    "agave": "Espadin",
    "extraction": "Tahona",
    "style": "Joven",
    "distillation": "Copper",
    "plantAge": "4-12 Years",
    "aroma": "Smoke · Vanilla · Alcohol · Peat · Vegetal · Agave (Cooked) · Campfire",
    "taste": "Sweet · Vanilla · Pepper · Smoke · Spice · Heat · Alcohol · Campfire",
    "sourceLabel": "La Chingada tasting archive · August 2019"
  }
};

